name: gemini_clone
description: A Flutter-based Gemini clone for internship assignment.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  flutter_screenutil: ^5.9.3
  intl: ^0.18.1
  hive: ^2.2.3
  get_storage: ^2.0.0
  hive_flutter: ^1.1.0
  retry: ^3.1.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/user_avatar.png
    - assets/images/ai_avatar.png